# Generated by Django 5.2.1 on 2025-05-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='odamlar',
        ),
        migrations.RemoveField(
            model_name='home',
            name='xonadon',
        ),
        migrations.AddField(
            model_name='contactus',
            name='odamlar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactus',
            name='xonadon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='text',
            field=models.TextField(),
        ),
    ]
