# Generated by Django 5.2.1 on 2025-05-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_home_odamlar_remove_home_xonadon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
