# Generated by Django 5.2.12 on 2026-04-02 15:21

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aloqa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aloqa',
        ),
        migrations.AlterField(
            model_name='home',
            name='text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
