# Generated by Django 5.2.12 on 2026-04-02 17:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_aloqa_alter_home_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
