# Generated by Django 5.2.12 on 2026-04-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contactus_email_alter_contactus_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('ism', models.CharField(max_length=50)),
                ('familya', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nomer', models.CharField(max_length=20)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], default='erkak', max_length=10)),
                ('daraja', models.CharField(choices=[('fuqaro', 'Oddiy fuqaro'), ('rais', 'Rais'), ('muovin', 'Muovin')], default='fuqaro', max_length=20)),
            ],
            options={
                'verbose_name': "Ro'yxatdan o'tgan foydalanuvchi",
                'verbose_name_plural': "Ro'yxatdan o'tgan foydalanuvchilar",
            },
        ),
    ]
