# Generated by Django 5.2.12 on 2026-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='jinsi',
            field=models.CharField(choices=[('jinsi', 'Jinsi tanlang'), ('erkak', 'Erkak'), ('ayol', 'Ayol')], default='erkak', max_length=10),
        ),
    ]
