# Generated by Django 6.0.4 on 2026-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userregistration_jinsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='jinsi',
            field=models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], default='jinsi', max_length=10),
        ),
    ]
