# Generated by Django 6.0.4 on 2026-04-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userregistration_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='home.userregistration')),
            ],
            options={
                'verbose_name': 'SMS kod',
                'verbose_name_plural': 'SMS kodlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
