# Generated by Django 5.2.12 on 2026-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
