# Generated by Django 6.0.4 on 2026-04-10 19:14

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_userregistration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('sarlavha', models.CharField(max_length=255)),
                ('matn', ckeditor_uploader.fields.RichTextUploadingField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='elonlar/')),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sorovnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('savol', models.CharField(max_length=255)),
                ('variant_a', models.CharField(max_length=100)),
                ('variant_b', models.CharField(max_length=100)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
