# Generated by Django 6.0.4 on 2026-04-10 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_elon_sorovnoma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ovoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanlov', models.CharField(max_length=10)),
                ('sorovnoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovozlar', to='home.sorovnoma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userregistration')),
            ],
            options={
                'unique_together': {('user', 'sorovnoma')},
            },
        ),
    ]
