# Generated by Django 5.2.12 on 2026-04-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_ovoz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Aloqa Xabari',
                'verbose_name_plural': 'Aloqa Xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Manzil va Aloqa', 'verbose_name_plural': 'Manzil va Aloqa'},
        ),
    ]
